## Broadcasting

In [1]:
import numpy as np

v = np.array([1,2,3,5])
print(v+2) # The 2 is added upon each value in the matrix

[3 4 5 7]


## Matrices as Linear Mappings

The rank of a matrix is the maximum number of linearly independent row vectors or column vectors in the matrix. In other words, it's the maximum number of dimensions spanned by all the vectors (rows or columns) of the matrix.

For example, consider the following 3x3 matrix:

[1 0 0]
[0 1 0] 
[0 0 1]

The rank of this matrix is 3 because each row (or column) is linearly independent - that is, no row (or column) can be written as a linear combination of the others.

Conversely, consider this 3x3 matrix:

[1 2 3]
[2 4 6]
[3 6 9]

The rank of this matrix is 1. Despite having 3 rows and 3 columns, all rows (and columns) can be written as a linear combination of any other single row (or column). For example, the second row is just the first row multiplied by 2, and the third row is the first row multiplied by 3.

The rank of a matrix provides important information about the matrix, including the solutions to systems of linear equations represented by the matrix. If the rank of the coefficient matrix is equal to the rank of the augmented matrix (the coefficient matrix with an extra column representing the constants on the right side of the equations), then the system has a solution. Otherwise, the system has no solution.

## Determinants and Traces

A matrix has a determinant if and only if it is a square matrix. that depends on the elements of the matrix. It captures info about what happens to the input space when it is multiplied by the matrix. 

if the columns of a matrix are linarly dependent, then its determinant will be zero. This is one way to check if a square matrix has an inverse

A 2 x 2 matrix A = [[a,b], [c,d]] has a determinant, 
det(A) = |[a,b], [c, d] | = ad - bc

## Eigenvalues and Eigenvectors

Let A be a n x n matrix. Then lambda is an eigenvalue of A, and x is the corresponding eigenvector of A if Ax = (lambda)x

A maps x is just to a scalar times x. It just stretches or shrinkg and/or flips it

To find the eigenvalues and eigen vectors, we need to know det(A-lambdaIn) = 0

say A = np.array([[3,1], [2,4]]), then 
det(A-lambdaI) = det([[3 - lambda, 1], [2, 4 - lambda]]) = 0

In [2]:
import numpy as np
A = np.array([[3,1],[2,4]])
np.linalg.eig(A)

(array([2., 5.]),
 array([[-0.70710678, -0.4472136 ],
        [ 0.70710678, -0.89442719]]))

In [4]:
vals, vecs = np.linalg.eig(A)
print(vals)
print(vecs)

[2. 5.]
[[-0.70710678 -0.4472136 ]
 [ 0.70710678 -0.89442719]]


In [5]:
np.linalg.norm(vecs[:,0]), np.linalg.norm(vecs[:,1])

(0.9999999999999999, 0.9999999999999999)

In [6]:
A@vecs.T[0], vals[0]*vecs.T[0]

(array([-1.41421356,  1.41421356]), array([-1.41421356,  1.41421356]))